// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestTask.PostgreSQL;

namespace TestTask.PostgreSQL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210320105332_changerelationship")]
    partial class changerelationship
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("TestTask.PostgreSQL.Entities.PFR", b =>
                {
                    b.Property<string>("Snils")
                        .HasColumnType("text");

                    b.Property<int?>("Period")
                        .HasColumnType("integer");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<double?>("Sum")
                        .HasColumnType("double precision");

                    b.HasKey("Snils");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("PFRs");
                });

            modelBuilder.Entity("TestTask.PostgreSQL.Entities.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Birthday")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("PersonId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("TestTask.PostgreSQL.Entities.PFR", b =>
                {
                    b.HasOne("TestTask.PostgreSQL.Entities.Person", "person")
                        .WithOne("Pfr")
                        .HasForeignKey("TestTask.PostgreSQL.Entities.PFR", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("person");
                });

            modelBuilder.Entity("TestTask.PostgreSQL.Entities.Person", b =>
                {
                    b.Navigation("Pfr");
                });
#pragma warning restore 612, 618
        }
    }
}
